export interface Issue {
    url: string,
    repository_url: string,
    labels_url: string,
    comments_url: string,
    events_url: string,
    html_url: string,
    id: number,
    pull_request: object,
    body: string,
    node_id: string,
    number: number,
    title: string,
    user: object,
    labels: Array<any>,
    state: string,
    locked: boolean,
    assignees: Array<object>,
    comments: number,
    created_at: string,
    milestone?: object,
    assignee?: object,
    updated_at?: string,
    closed_at?: string,
    author_association?: string,
    active_lock_reason?: any,
    performed_via_github_app?: boolean
}